### ISSUE TITLE
Missing splitters/sar/sar_split

### ISSUE THREAD

**Issue by SushiInYourFace** [vktec/rift#1]
The startup script appears to require executing ./splitters/sar/sar_split to work, but, when downloading rift, this appears to be in the gitignore. I do not know if I'm supposed to add this myself, or if there's some mistake in the code, either in this file being in the gitignore, or the startup script requiring the file. If it is the case of needing to manually add the file, then a readme explaining what to do would be helpful. 
![image](https://user-images.githubusercontent.com/59146652/103310450-a89afc80-49e5-11eb-95f8-d10c25d2eded.png)

**Comment by vktec** [comment]
You'll need to compile the splitter first. You can do that using `make -C splitters/sar`

Please bear in mind that this software is still pretty early in development and hasn't had much testing. If you're up for giving it a shot anyway, that's awesome! Feel free to report any bugs or difficulties you run into :)

**Comment by SushiInYourFace** [comment]
Thank you for the super quick response! That would also explain the lack of a readme lol, as writing the code is obviously a much larger priority than explaining how to use it.

**Comment by mlugg** [comment]
Also bear in mind that you should open rift only after Portal 2 has loaded; without the hook to SAR, the splitter will immediately exit and the timer will cease to function.
